# Generated by Django 4.2.17 on 2026-05-11 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.CharField(choices=[('GP', 'General Practice'), ('CARDIO', 'Cardiology'), ('DERM', 'Dermatology'), ('NEURO', 'Neurology'), ('ORTHO', 'Orthopedics'), ('PEDIA', 'Pediatrics'), ('PSYCH', 'Psychiatry'), ('GYNEC', 'Gynecology'), ('OPHTH', 'Ophthalmology'), ('ENT', 'ENT (Ear, Nose & Throat)'), ('URO', 'Urology'), ('ONCO', 'Oncology')], max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('available_monday', models.BooleanField(default=True)),
                ('available_tuesday', models.BooleanField(default=True)),
                ('available_wednesday', models.BooleanField(default=True)),
                ('available_thursday', models.BooleanField(default=True)),
                ('available_friday', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
